In [1]:
import selenium

In [2]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
import time

In [3]:
import warnings
warnings.filterwarnings('ignore')

1. Write a python program which searches all the product under a particular product from www.amazon.in. The
product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for
guitars.

In [47]:
driver = webdriver.Chrome()

In [48]:
driver.get('https://www.amazon.in/')

In [49]:
product = input('Enter a product to be searched :')

Enter a product to be searched :guitar

In [50]:
search = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search.send_keys(product)
search.submit()

2. In the above question, now scrape the following details of each product listed in first 3 pages of your search
results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then
scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [51]:
Name = []
Price = []
Expected_Delivery =[]
url = []

In [52]:
for i in driver.find_elements(By.XPATH,"//span[@class = 'a-size-base-plus a-color-base a-text-normal']"):
    Name.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-price-whole']"):
    Price.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-color-base a-text-bold']"):
    Expected_Delivery.append(i.text)
for i in driver.find_elements(By.XPATH,"//a[@class='a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal']"):
    url.append(i.get_attribute('href'))

In [54]:
next = driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[1]/div/span[1]/div[1]/div[69]/div/div/span/a[3]')
next.click()

In [55]:
for i in driver.find_elements(By.XPATH,"//span[@class = 'a-size-base-plus a-color-base a-text-normal']"):
    Name.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-price-whole']"):
    Price.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-color-base a-text-bold']"):
    Expected_Delivery.append(i.text)
for i in driver.find_elements(By.XPATH,"//a[@class='a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal']"):
    url.append(i.get_attribute('href'))

In [56]:
next = driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[1]/div/span[1]/div[1]/div[66]/div/div/span/a[4]')
next.click()

In [57]:
for i in driver.find_elements(By.XPATH,"//span[@class = 'a-size-base-plus a-color-base a-text-normal']"):
    Name.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-price-whole']"):
    Price.append(i.text)
for i in driver.find_elements(By.XPATH,"//span[@class='a-color-base a-text-bold']"):
    Expected_Delivery.append(i.text)
for i in driver.find_elements(By.XPATH,"//a[@class='a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal']"):
    url.append(i.get_attribute('href'))

In [62]:
print(len(Name),len(Price),len(Expected_Delivery),len(url))

184 190 10 186

In [63]:
Guitars= pd.DataFrame({'Brand Name': Name[0:178],'Price':Price[0:178],'Expected Delivery':Expected_Delivery[0:178],'Product URL':url[0:178]})

In [43]:
Guitars.to_csv('Guitars.csv')

In [67]:
Data = pd.read_csv('Guitars.csv')
Data

,Unnamed: 0,Brand Name,Price,Expected Delivery,Product URL
0,0,"Kadence rosewood Guitar Frontier Series, Elect...","6,999","Saturday, 5 August",https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,1,Kadence Slowhand Premium Jumbo Semi Acoustic G...,"6,999","Thursday, 3 August",https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,2,Henrix 38C 38 Inch Cutaway Acoustic Guitar Wit...,"7,599","Thursday, 3 August",https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,3,Kadence Frontier guitar with Online Guitar lea...,"4,999","Thursday, 3 August",https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,4,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","11,999","Thursday, 3 August",https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...
110,110,Kadence GenZ Guitar (with Guitar learning cour...,"10,544","Sunday, 6 August",https://www.amazon.in/Ibanez-GSA60-Electric-Gu...
111,111,JUAREZ 38 Inches Lindenwood Acoustic Guitar Wi...,"4,990","Friday, 4 August",https://www.amazon.in/JUAREZ-JRZ38C-Handed-Aco...
112,112,"Yamaha FS100C Acoustic Guitar, Natural","5,999","Thursday, 3 August",https://www.amazon.in/Kadence-Acoustica-Acoust...
113,113,YAMAHA WINNING STROKE F280 Acoustic Guitar wit...,"3,179","Monday, 7 August",https://www.amazon.in/Intern-INT-38C-VT-G-Guit...
114,114,"JUAREZ Arpeggio Guitar JRA39SR-BK-K, black","9,789","Monday, 7 August",https://www.amazon.in/Kadence-Frontier-Acousti...

In [68]:
driver.close()

3. Write a python program to access the search bar and search button on images.google.com and scrape 10
images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [21]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
import time

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
driver =webdriver.Chrome()

In [24]:
driver.get('https://images.google.com/')

In [25]:
search = driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search.send_keys('fruits')
search.submit()

In [26]:
Fruits_images = []
for i in driver.find_elements(By.XPATH,'//img[@class = "rg_i Q4LuWd"]'):
    Fruits_images.append(i.get_attribute('src'))

In [27]:
search = driver.find_element(By.XPATH,'/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input')
search.clear()
delay = 2
search.send_keys('Cars')
search.submit()

In [28]:
Car = []
for i in driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]'):
    Car.append(i.get_attribute('src'))

In [29]:
search = driver.find_element(By.XPATH,'/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input')
search.clear()
delay = 5
search.send_keys('Machine Learning')
search.submit()

In [30]:
Machine_Learing = []
for i in driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]'):
    Machine_Learing.append(i.get_attribute('src'))

In [31]:
search = driver.find_element(By.XPATH,'/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input')
search.clear()
delay = 5
search.send_keys('Guitar')
search.submit()

In [32]:
Guitar = []
for i in driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]'):
    Guitar.append(i.get_attribute('src'))

In [33]:
search = driver.find_element(By.XPATH,'/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input')
search.clear()
delay = 5
search.send_keys('Cakes')
search.submit()

In [34]:
Cakes = []
for i in driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]'):
    Cakes.append(i.get_attribute('src'))

In [36]:
print(len(Fruits_images),len(Car),len(Machine_Learing),len(Guitar),len(Cakes))

48 46 48 48 48

In [38]:
Data = pd.DataFrame({'Fruits':Fruits_images[0:10],'Cars':Car[0:10],'Machine Learning':Machine_Learing[0:10],'Guitar':Guitar[0:10],'Cakes':Cakes[0:10]})

In [40]:
Data.to_csv('image.csv')

In [41]:
Data1 = pd.read_csv('image.csv')
Data1.drop('Unnamed: 0',axis =1)

,Fruits,Cars,Machine Learning,Guitar,Cakes
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
5,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
6,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
7,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
8,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
9,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."

In [42]:
driver.close()

4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the
details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [69]:
driver = webdriver.Chrome()

In [70]:
driver.get('https://www.flipkart.com/')

In [71]:
close = driver.find_element(By.XPATH,'/html/body/div[2]/div/div/button')
close.click()

In [72]:
search = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
search.send_keys('oneplus nord')
search.submit()

In [73]:
Brand = []
Name =[]
Color=[]
for i in driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]'):
    Brand.append(i.text.split(' ')[0])
    Name.append(i.text)
    co = i.text.split('(')[-1]
    Color.append(co.split(',')[0])

In [74]:
RAM =[]
ROM =[]
Primary_Camera =[]
Display=[]
Battery =[]

for i in driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]'):
    RA = i.text.split('\n')[0]
    RAM.append(RA.split('|')[0])
    ROM.append(RA.split('|')[1])
    
    Display.append(i.text.split('\n')[1])
    Battery.append(i.text.split('\n')[-2])
    
    Camera = i.text.split('\n')[2]
    Primary_Camera.append(Camera.split('|')[0])

In [76]:
Price = []
Url=[]
for i in driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]'):
    Price.append(i.text)
for i in driver.find_elements(By.XPATH,'//a[@class="_1fQZEK"]'):
    Url.append(i.get_attribute('href'))

In [77]:
print(len(Brand),len(Name),len(Color),len(RAM),len(ROM),len(Primary_Camera),len(Display),len(Battery),len(Price),len(Url))

24 24 24 24 24 24 24 24 24 24

In [78]:
Phone = pd.DataFrame({'Brand Name':Brand,'Phone Name':Name,'Colour':Color,'Phone RAM':RAM,'Phone ROM':ROM,'Primary Camera':Primary_Camera,'Phone Display':Display,'Phone Battery':Battery,'Price':Price,'Url':Url})

In [79]:
Phone.to_csv('Phone.csv')

In [80]:
pd.read_csv('Phone.csv')

,Unnamed: 0,Brand Name,Phone Name,Colour,Phone RAM,Phone ROM,Primary Camera,Phone Display,Phone Battery,Price,Url
0,0,OnePlus,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)",Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,"₹17,665",https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,1,OnePlus,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",Black Dusk,6 GB RAM,128 GB ROM,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,"₹17,589",https://www.flipkart.com/oneplus-nord-ce-2-lit...
2,2,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)",Pastel Lime,8 GB RAM,128 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹19,999",https://www.flipkart.com/oneplus-nord-ce-3-lit...
3,3,OnePlus,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)",Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹27,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
4,4,OnePlus,"OnePlus Nord 3 5G (Misty Green, 256 GB)",Misty Green,16 GB RAM,256 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹37,883",https://www.flipkart.com/oneplus-nord-3-5g-mis...
5,5,OnePlus,"OnePlus Nord 3 5G (Tempest Gray, 256 GB)",Tempest Gray,16 GB RAM,256 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹37,615",https://www.flipkart.com/oneplus-nord-3-5g-tem...
6,6,OnePlus,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)",Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,938",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
7,7,OnePlus,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)",Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
8,8,OnePlus,"OnePlus Nord (Gray Onyx, 64 GB)",Gray Onyx,6 GB RAM,64 GB ROM,48MP + 8MP,16.36 cm (6.44 inch) Full HD+ Display,Qualcomm® Snapdragon™ 765G Processor,"₹23,990",https://www.flipkart.com/oneplus-nord-gray-ony...
9,9,OnePlus,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)",Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,750",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
10,10,OnePlus,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)",Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,890",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
11,11,OnePlus,"OnePlus Nord CE 2 5G (Gray Mirror, 128 GB)",Gray Mirror,8 GB RAM,128 GB ROM,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹24,999",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
12,12,OnePlus,"OnePlus Nord CE 5G (Silver Ray, 256 GB)",Silver Ray,12 GB RAM,256 GB ROM,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹27,990",https://www.flipkart.com/oneplus-nord-ce-5g-si...
13,13,OnePlus,"OnePlus Nord 3 5G (Tempest Gray, 128 GB)",Tempest Gray,8 GB RAM,128 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹33,368",https://www.flipkart.com/oneplus-nord-3-5g-tem...
14,14,OnePlus,"OnePlus Nord 3 5G (Misty Green, 128 GB)",Misty Green,8 GB RAM,128 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹33,423",https://www.flipkart.com/oneplus-nord-3-5g-mis...
15,15,OnePlus,"OnePlus Nord 2 5G (Blue Haze, 256 GB)",Blue Haze,12 GB RAM,256 GB ROM,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹32,990",https://www.flipkart.com/oneplus-nord-2-5g-blu...
16,16,OnePlus,"OnePlus Nord 2 5G (Gray Sierra, 128 GB)",Gray Sierra,8 GB RAM,128 GB ROM,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹29,999",https://www.flipkart.com/oneplus-nord-2-5g-gra...
17,17,OnePlus,"OnePlus Nord CE 5G (Blue Void, 256 GB)",Blue Void,12 GB RAM,256 GB ROM,64MP Rear Camera,16.33 cm (6.43 inch) Display,Qualcomm Snapdragon Octa Core 750G 5G Processo...,"₹27,999",https://www.flipkart.com/oneplus-nord-ce-5g-bl...
18,18,OnePlus,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)",Bahama Blue,8 GB RAM,128 GB ROM,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹24,999",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
19,19,OnePlus,"OnePlus Nord 2 5G (Green Wood, 256 GB)",Green Wood,12 GB RAM,256 GB ROM,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹33,999",https://www.flipkart.com/oneplus-nord-2-5g-gre...
20,20,OnePlus,"OnePlus Nord 2 5G (PAC-MAN, 256 GB)",PAC-MAN,12 GB RAM,256 GB ROM,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹35,999",https://www.flipkart.com/oneplus-nord-2-5g-pac...
21,21,OnePlus,"OnePlus Nord (Blue Marble, 128 GB)",Blue Marble,8 GB RAM,128 GB ROM,48MP + 8MP,16.36 cm (6.44 inch) Full HD+ Display,Qualcomm® Snapdragon™ 765G Processor,"₹25,990",https://www.flipkart.com/oneplus-nord-blue-mar...
22,22,OnePlus,"OnePlus Nord CE 5G (Charcoal Ink, 256 GB)",Charcoal Ink,12 GB RAM,256 GB ROM,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,"₹27,999",https://www.flipkart.com/oneplus-nord-ce-5g-ch...
23,23,OnePlus,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)",Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...

In [81]:
driver.close()

5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [9]:
driver = webdriver.Chrome()

In [10]:
driver.get('https://www.google.com/maps')

In [13]:
search = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div[3]/div[1]/div[1]/div/div[2]/form/input')
search.send_keys('Hyderabad')

In [14]:
location = driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div[3]/div[1]/div[1]/div/div[2]/div[1]/button')
location.click()

In [15]:
time.sleep(5)
url = driver.current_url

In [16]:
ll = url.split('/')[-2]

In [18]:
latitude = ll.split(',')[0].replace('@','')
longitude = ll.split(',')[1]

In [19]:
print('Latitude = ',latitude)
print('Longitude = ',longitude)

Latitude =  17.4120779
Longitude =  78.078379

In [20]:
driver.close()

6. Write a program to scrap all the available details of best gaming laptops from digit.in

In [25]:
driver = webdriver.Chrome()

In [26]:
driver.get('https://www.digit.in/')

In [27]:
Search = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[2]/a/img')
Search.click()
time.sleep(5)

In [28]:

here = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[3]/div/div/input')
here.send_keys('Best gaming laptop' + '\n')

In [29]:
Laptop = []
Date = []
for i in driver.find_elements(By.XPATH,'//div[@class="searchProduct-desc"]'):
    Laptop.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class = "searchPage"]'):
    Date.append(i.text.split('\n')[-1])

In [30]:
print(len(Laptop),len(Date))

10 10

In [31]:
digit = pd.DataFrame({'Laptop':Laptop, 'Date':Date})

In [32]:
digit.to_csv('digit.csv')

In [33]:
pd.read_csv('digit.csv')

   Unnamed: 0                                             Laptop          Date
0           0                              Asus TUF Gaming FX505  Jun 21, 2022
1           1                                       MSI GE60 2PE  Apr 09, 2019
2           2                           Dell Alienware (17-inch)  Apr 25, 2022
3           3                        Asus GTX980 Matrix Platinum  Jan 30, 2015
4           4                              Sony PlayStation Vita  Feb 18, 2012
5           5                                 Asus G750JX-CV069P  Nov 22, 2021
6           6                            Lenovo Ideapad gaming 3  Nov 09, 2022
7           7                     Cooler Master Storm Devastator  Jan 03, 2014
8           8  Best gaming laptop deals in the Amazon Grand G...  Jul 30, 2019
9           9  Digit Zero1 Awards 2021: Best Budget Gaming La...  Dec 17, 2021

In [34]:
driver.close()

7. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped:
“Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [9]:
driver = webdriver.Chrome()

In [10]:
driver.get('https://www.forbes.com/')

In [11]:
Acc = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/div[2]/button[2]/span')
Acc.click()
time.sleep(2)

In [13]:
Billionaires = driver.find_element(By.XPATH, '/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[1]')
Billionaires.click()

In [15]:
All_Billionaires = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/header/div[1]/div[1]/div[2]/ul/li[2]/div[2]/div[3]/ul/li[1]/a')
All_Billionaires.click() 
time.sleep(2)

In [20]:
Rank=[]
Name=[]
Net=[]
Age=[]
Source=[]
Industry=[]

for i in driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]'):
    Rank.append(i.text.split('\n')[0])
    Name.append(i.text.split('\n')[1])
    Net.append(i.text.split('\n')[2])
    Age.append(i.text.split('\n')[3])
    Source.append(i.text.split('\n')[4])
    Industry.append(i.text.split('\n')[5])

In [21]:
print(len(Rank),len(Name),len(Net),len(Age),len(Source),len(Industry))

199 199 199 199 199 199

In [22]:
Billionaires = pd.DataFrame({'Rank':Rank,'Name':Name,'Net Worth':Net,'Age':Age,'Source':Source,'Industry':Industry})

In [23]:
Billionaires.to_csv('Billionaires.csv')

In [24]:
pd.read_csv('Billionaires.csv')

,Unnamed: 0,Rank,Name,Net Worth,Age,Source,Industry
0,0,2,Elon Musk,$180 B,51.0,United States,"Tesla, SpaceX"
1,1,3,Jeff Bezos,$114 B,59.0,United States,Amazon
2,2,4,Larry Ellison,$107 B,78.0,United States,Oracle
3,3,5,Warren Buffett,$106 B,92.0,United States,Berkshire Hathaway
4,4,6,Bill Gates,$104 B,67.0,United States,Microsoft
...,...,...,...,...,...,...,...
194,194,195,Jin Baofang,$9.6 B,70.0,China,Solar panels
195,195,195,Luo Liguo & family,$9.6 B,67.0,China,Chemicals
196,196,195,Marijke Mars,$9.6 B,58.0,United States,"Candy, pet food"
197,197,195,Pamela Mars,$9.6 B,62.0,United States,"Candy, pet food"
198,198,195,Valerie Mars,$9.6 B,64.0,United States,"Candy, pet food"

In [25]:
driver.close()

8. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted
from any YouTube Video

In [26]:
driver = webdriver.Chrome()

In [27]:
driver.get('https://www.youtube.com')

In [29]:
search = driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/form/div[1]/div[1]/input')
search.send_keys('Vidya Vox - Shubha Mangalyam -(Official Video)')
search.submit()
delay = 5

In [30]:
Song = driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a/yt-formatted-string')
Song.click()

In [31]:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [33]:
Co = []
for i in driver.find_elements(By.XPATH,'//div[@class="style-scope ytd-comment-renderer"]'):
    Co.append(i.text)

In [34]:
Time = []
for i in driver.find_elements(By.XPATH,'//a[@class="yt-simple-endpoint style-scope yt-formatted-string"]'):
    Time.append(i.text)

In [47]:
Time = Time[82:582]

In [48]:
Comment = Co[0:500]

In [49]:
print(len(Time),len(Comment))

500 500

In [50]:
Song = pd.DataFrame({'Time':Time,'Comment':Comment})

In [52]:
Song.to_csv('Song.csv')

In [53]:
pd.read_csv('Song.csv')

,Unnamed: 0,Time,Comment
0,0,2 months ago,NaN
1,1,2 months ago,NaN
2,2,2 months ago,@VidyaVox\n2 months ago (edited)\nThank you gu...
3,3,3 weeks ago,NaN
4,4,2 months ago,@VidyaVox\n2 months ago (edited)\nThank you gu...
...,...,...,...
495,495,2 months ago,NaN
496,496,2 months ago,NaN
497,497,#kerala,@ruxg1459\n1 month ago\nWe are using this in S...
498,498,#godsowncountry,NaN
499,499,2 months ago,@ruxg1459\n1 month ago\nWe are using this in S...

In [54]:
driver.close()

9. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall
reviews, privates from price, dorms from price, facilities and property description.

In [4]:
driver = webdriver.Chrome()

In [5]:
driver.get('https://www.hostelworld.com/')

In [6]:
Accept = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[4]/div/div/div[2]/button[2]')
Accept.click()
time.sleep(2)

In [7]:
search = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
search.send_keys('london')

In [8]:
london = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]/button/div[2]/div[1]')
london.click()

In [9]:
go = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button')
go.click()

In [17]:
Name =[]
Distance =[]
Ratings =[]
Review =[]
Private_Price=[]
Dorms_Price =[]
for i in driver.find_elements(By.XPATH,'//div[@class="property-name"]'):
    Name.append(i.text)
for i in driver.find_elements(By.XPATH,'//span[@class="distance-description"]'):
    Distance.append(i.text)
for i in driver.find_elements(By.XPATH,'//span[@class="number"]'):
    Ratings.append(i.text)
for i in driver.find_elements(By.XPATH,'//span[@class="keyword"]'):
    Review.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class="accommodation-price single-row"]'):
    Private_Price.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class="property-accommodation-price"]'):
    Dorms_Price.append(i.text)

In [18]:
print(len(Name),len(Distance),len(Ratings),len(Review),len(Private_Price),len(Dorms_Price))

32 30 32 31 38 62

In [19]:
Hostel = pd.DataFrame({'Hostel Name':Name[0:30],'Distance':Distance[0:30],'Ratings':Ratings[0:30],'Reviews':Review[0:30],'Private Price':Private_Price[0:30],'Dorms_Price':Dorms_Price[0:30]})

In [20]:
Hostel.to_csv('Hostels.csv')

In [21]:
pd.read_csv('Hostels.csv')

,Unnamed: 0,Hostel Name,Distance,Ratings,Reviews,Private Price,Dorms_Price
0,0,St Christopher's Village,- 3.6km from city centre,8.1,Fabulous,£189\n£151,From\n£23
1,1,Clink261,- 5.5km from city centre,8.2,Fabulous,£39\n£31,From\n£28
2,2,Wombat's City Hostel London,- 1.8km from city centre,9.0,Superb,£110,-20%\nPrivates From\n£189\n£151
3,3,Onefam Notting Hill by Hostel One,- 3km from city centre,9.6,Superb,£34,-20%\nDorms From\n£39\n£31
4,4,St Christopher's Village,- 6.1km from city centre,8.1,Fabulous,£26\n£23,Privates From\n£110
5,5,Generator London,- 5.4km from city centre,7.6,Very Good,£111,Dorms From\n£34
6,6,NX London Hostel,- 4.3km from city centre,8.2,Fabulous,£21,No Privates Available
7,7,Urbany Hostel London,- 1.7km from city centre,9.5,Superb,£31\n£25,-10%\nDorms From\n£26\n£23
8,8,Astor Hyde Park,- 4.2km from city centre,8.4,Fabulous,£134,Privates From\n£111
9,9,Safestay London Elephant & Castle,- 5.8km from city centre,7.2,Very Good,£41,Dorms From\n£21
10,10,Phoenix Hostel,- 5km from city centre,8.0,Fabulous,£18,No Privates Available
11,11,Safestay London Kensington Holland Park,- 3.2km from city centre,7.0,Very Good,£145,-19%\nDorms From\n£31\n£25
12,12,Smart Hyde Park Inn Hostel,- 1.7km from city centre,7.5,Very Good,£20,Privates From\n£134
13,13,Clink261,- 10km from city centre,8.2,Fabulous,£21\n£20,Dorms From\n£41
14,14,Destinations Hostels @ The Gallery,- 11.9km from city centre,9.2,Superb,£17,No Privates Available
15,15,No.8 Willesden Hostel London,- 9km from city centre,6.4,Good,£24\n£22,Dorms From\n£18
16,16,London Backpackers,- 3.3km from city centre,7.6,Very Good,£28,Privates From\n£145
17,17,No.8 Seven Sisters,- 5.7km from city centre,5.2,Superb,£53,Dorms From\n£20
18,18,International Students House,- 1.8km from city centre,9.0,Very Good,£9,No Privates Available
19,19,Queen Elizabeth Chelsea,- 1.8km from city centre,7.3,Very Good,£69,-5%\nDorms From\n£21\n£20
20,20,St Christopher's Inn - London Bridge,- 7.5km from city centre,7.8,Very Good,£17,No Privates Available
21,21,Astor Victoria,- 5.5km from city centre,7.0,Very Good,£11,Dorms From\n£17
22,22,St Christopher's Hammersmith,- 2.1km from city centre,7.4,Very Good,£66,No Privates Available
23,23,Saint James Backpackers,- 3.6km from city centre,7.7,Fabulous,£27,-10%\nDorms From\n£24\n£22
24,24,YHA London Oxford Street,- 7.6km from city centre,8.6,Fabulous,£29\n£26,No Privates Available
25,25,Prime Backpackers Angel,- 3.2km from city centre,8.0,Very Good,£18,Dorms From\n£28
26,26,St Christopher's Greenwich,- 4.3km from city centre,7.8,Fabulous,£18\n£16,No Privates Available
27,27,St Christopher's Inn - Liverpool Street,- 0.5km from city centre,8.1,Very Good,£73,Dorms From\n£53
28,28,St Christopher's Camden,- 4.2km from city centre,7.0,Fabulous,£33,No Privates Available
29,29,"PubLove @ The Steam Engine, Waterloo",- 4.9km from city centre,8.2,Very Good,£120,Dorms From\n£9